# 메트릭 서버(파드의 자원상황 모니터링 툴) 설치
# kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

# Horizontal Pod Autoscaler
# 컨테이너 자동확장
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ordersystem-hpa
  namespace: jiho
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ordersystem-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

# 부하 테스트
# kubectl exec -it 파드명 /bin/bash -n jiho
# while true; do curl -s http:/ordersystem-service/product/list; done

# 부하 모니터링
# -w : watch옵션
# kubectl get hpa ordersystem-hpa -n jiho -w