apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersystem-deployment  # 올바른 이름으로 수정
  namespace: jiho
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordersystem  # 단순 키-값 쌍으로 수정
  template:
    metadata:
      labels:
        app: ordersystem
    spec:
      containers:
      - name: ordersystem
        # aws의 ecr 주소 사용
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/jiho-ordersystem:latest
        ports:
        - containerPort: 8080
        resources:
          # 최대 할당가능량
          limits:
            cpu: "0.2"
            memory: "250Mi"
          # 최소 할당량
          requests:
            cpu: "0.2"
            memory: "250Mi"
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: jiho-app-secrets
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: jiho-app-secrets
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: jiho-app-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: jiho-app-secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: jiho-app-secrets
        - name: JWT_SECRET_RT
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET_RT
              name: jiho-app-secrets
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: jiho-app-secrets
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: jiho-app-secrets