spring:
  redis:
    host:  ${REDIS_HOST}
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/ordersystem
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 5
  jpa:
    database: mysql
    database-platform:  org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  application:
    name: product-service

logging:
  level:
    root: info
jwt:
  expiration: 30
  secretKey: my_token_secret
  expirationRt: 14400
  secretKeyRt: my_refresh_token_secret

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key: ${{secrets.S3_KEY}}
      secret-key: ${{secrets.S3_SECRET}}
    region:
      static: ${{secrets.S3_REGION}}
    s3:
      bucket: ${{secrets.S3_BUCKET}}
