apiVersion: v1
kind: Service
metadata:
  name: ordersystem-service
  namespace: jiho
spec:
# Ingress를 적용하기 위해 ClusterIp로 변경
  type: ClusterIP
  selector:
    app: ordersystem
  ports:
  - name: http
    port: 80
    targetPort: 8080