spring:
  redis:
    host: ${REDIS_HOST}
    port: 6379


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/spring_order_msa
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # spring에서 db로의 커넥션 개수 제한
    # 기본적으로 대략 10 가량의 커넥션이 1개의 서버에서 발생. 
    tomcat: 
      max-active: 5

  jpa:
    database: mysql
    database-platform:  org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
logging:
  level:
    root: info
jwt:
  expiration: 30
  secretKey: my_token_secret
  expirationRt: 14400
  secretKeyRt: my_refresh_token_secret

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key: xxxx
      secret-key: yyyyy
    region:
      static: ap-northeast-2
    s3:
      bucket: jiho-file
